version: '3.8'
services:
  ingame-price-web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "7860:7860"
    volumes:
      - .:/app

  # ingame-price-main:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   entrypoint: ["/bin/true"]
  #   volumes:
  #     - .:/app
